import type { Metadata } from "next";
import ToasterContext from "./context/ToasterContext"
import AuthContext from "./context/AuthContext"
import { Inter } from "next/font/google";
import "./globals.css";
import ActiveStatus from "./components/ActiveStatus";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IBY Messenger",
  description: "Generated by Vishwaa",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <ToasterContext />
          <ActiveStatus />
          {children}
        </AuthContext>
        </body>
    </html>
  );
}
